version:  '3'
services:
  datascience-notebook:
      image:    edrixs
      volumes:
        - ./:/home/rixs
      working_dir:    /home/rixs
      ports:
        - 8888:8888
      command: "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser"

